/**
 * Unit tests for the scaffold gallery's protected-set (read-only) affordances:
 *   npx vitest run tests/interfaces/web_terminal/claude-setup-badge.test.mjs
 *
 * The gallery is the panel an operator actually opens to read and edit the
 * agent's setup files, and some of those files are now reserved: the write
 * gates refuse a save, a claim, or a delete aimed at them and answer 403 with
 * the channel that owns the change instead. An artifact carrying
 * `read_only: true` is that same verdict, precomputed at list time.
 *
 * These tests pin the client's half of that contract:
 *   - the badge, on the card and in the detail header, so the fact is met
 *     while reading rather than only when a save comes back refused;
 *   - the controls that would attempt a refused write (Edit, Save, the
 *     ownership button) rendered disabled, and the editors rendered
 *     un-typeable -- including settings.json, whose Preview offers no
 *     editable control at all;
 *   - the panel copy that says what to do instead of saving here;
 *   - and, because the server is the enforcement and the client only mirrors
 *     it, the 403 refusal detail reaching the error banner verbatim when a
 *     write goes out anyway.
 *
 * Fake `gallery` host objects stand in for the ArtifactGallery instance --
 * the same "pass `this`" shape the real class uses -- mirroring
 * scaffold-detail.test.mjs and scaffold-edit.test.mjs.
 *
 * NOTE: imported by RELATIVE path -- these modules live under web_terminal,
 * not design-system, so the `/design-system/js/*` alias does not apply.
 */

import { test, expect, vi, describe, beforeEach, afterEach } from 'vitest';

import { qs } from '../_support/dom.mjs';

import { createScaffoldGalleryCards } from '../../../src/osprey/interfaces/web_terminal/static/js/scaffold/cards.js';
import { createScaffoldGalleryDetail } from '../../../src/osprey/interfaces/web_terminal/static/js/scaffold/detail.js';
import { createScaffoldGalleryDetailContent } from '../../../src/osprey/interfaces/web_terminal/static/js/scaffold/detail-content.js';
import { createScaffoldGalleryEditForm } from '../../../src/osprey/interfaces/web_terminal/static/js/scaffold/edit-form.js';
import { createScaffoldGalleryEdit } from '../../../src/osprey/interfaces/web_terminal/static/js/scaffold/edit.js';

/** A reserved artifact: the build profile renders it, so the panel cannot save it. */
const RESERVED = {
  name: 'settings-json',
  category: 'config',
  status: 'framework',
  output_path: '.claude/settings.json',
  language: 'json',
  read_only: true,
};

/** An ordinary artifact the panel may write. */
const WRITABLE = {
  name: 'reviewer',
  category: 'agents',
  status: 'user-owned',
  output_path: '.claude/agents/reviewer.md',
  language: 'markdown',
  read_only: false,
};

/**
 * The 403 detail `PUT /api/scaffold/{name}/override` answers with for a
 * reserved artifact: ProtectedArtifactError's message, built by
 * `_refuse_reserved` (scaffold_gallery_service.py) from the canonical name and
 * the channel table, and passed through by the route as `detail=str(e)`. The
 * channel text is `.claude/settings.json`'s entry in RESERVED_PROJECT_PATHS.
 */
const REFUSAL_DETAIL =
  "'settings-json' belongs to the profile's `config:` keys "
  + '(`claude_code.permissions`, `claude_code.hooks`, `artifacts.hooks`). '
  + 'NOTHING WAS WRITTEN.';

/**
 * What a refused claim answers with instead: `scaffold_override` raises
 * ScaffoldClaimError, which the app-level handler renders as a 409 -- a
 * different status and a different message from the save refusal above, but
 * the same trip through `apiRequest` into the banner.
 */
const CLAIM_REFUSAL_DETAIL =
  "'settings-json' is generated by the framework render — carry the change as "
  + 'a `config:` key instead.';

/**
 * The transitional payload: an artifact as the service serves it today, with
 * no `read_only` key at all. Absent must read as writable.
 * @param {any} artifact
 * @returns {any}
 */
function withoutReadOnlyKey(artifact) {
  const copy = { ...artifact };
  delete copy.read_only;
  return copy;
}

/** @param {Partial<any>} [overrides] */
function makeDetailGallery(overrides = {}) {
  return /** @type {any} */ ({
    selectedArtifact: null,
    currentView: 'gallery',
    detailMode: 'preview',
    editDirty: false,
    artifacts: [],
    galleryView: document.createElement('div'),
    detailView: document.createElement('div'),
    detailHeaderEl: document.createElement('div'),
    detailModesEl: document.createElement('div'),
    detailContentEl: document.createElement('div'),
    onDetailOpen: null,
    load: () => Promise.resolve(),
    renderDetailModes: () => {},
    closeDetail: vi.fn(),
    releaseToFramework: vi.fn(),
    takeOwnership: vi.fn(),
    handleEditFramework: vi.fn(),
    discardEdits: vi.fn(),
    saveOverride: vi.fn(),
    renderEdit: vi.fn(() => Promise.resolve()),
    ...overrides,
  });
}

/**
 * Render one artifact's card into a fresh section element.
 * @param {any} artifact
 * @param {string} [cat]
 * @returns {HTMLElement}
 */
function renderCard(artifact, cat = 'agents') {
  const section = document.createElement('div');
  const { renderArtifactCard } = createScaffoldGalleryCards({ openDetail: vi.fn() });
  renderArtifactCard(section, artifact, cat);
  return /** @type {HTMLElement} */ (section.firstElementChild);
}

/**
 * Open an artifact's detail view and return the gallery host, with
 * renderDetailModes wired to the factory's own so mode re-renders are real
 * (the same delegation ArtifactGallery does).
 * @param {any} artifact
 */
function openDetail(artifact) {
  const gallery = makeDetailGallery({ selectedArtifact: artifact });
  const detail = createScaffoldGalleryDetail(gallery);
  gallery.renderDetailModes = detail.renderDetailModes;
  gallery.detailHeaderEl.className = 'prompts-detail-header';
  detail.openDetail(artifact);
  return { gallery, detail };
}

beforeEach(() => {
  vi.stubGlobal('confirm', vi.fn(() => true));
  vi.stubGlobal('alert', vi.fn());
  // Default content fetch, so the detail view's preview render resolves
  // instead of reaching for a real localhost. Tests that care about the
  // response override this with their own stub.
  vi.stubGlobal(
    'fetch',
    vi.fn(async () => ({
      ok: true,
      json: async () => ({ content: '{"model": "opus"}', language: 'json' }),
    }))
  );
});

afterEach(() => {
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe('read-only badge', () => {
  test('renders on a reserved artifact card, and not on a writable one', () => {
    const reservedCard = renderCard(RESERVED, 'config');
    const writableCard = renderCard(WRITABLE);

    expect(qs(reservedCard, '.prompts-badge.read-only')).toBeTruthy();
    expect(reservedCard.classList.contains('prompts-card-readonly')).toBe(true);

    expect(writableCard.querySelector('.prompts-badge.read-only')).toBeNull();
    expect(writableCard.classList.contains('prompts-card-readonly')).toBe(false);
  });

  test('does not displace the ownership badge -- the two say different things', () => {
    const card = renderCard(RESERVED, 'config');

    expect(qs(card, '.prompts-badge.framework').textContent).toBe('FRAMEWORK');
    expect(qs(card, '.prompts-badge.read-only').textContent).toBe('READ-ONLY');
  });

  test('carries the reason as its tooltip rather than only asserting the state', () => {
    const badge = qs(renderCard(RESERVED, 'config'), '.prompts-badge.read-only');

    expect(badge.title).toMatch(/build profile/i);
    expect(badge.title).toMatch(/refused/i);
  });

  test('covers a skill group when any member of it is reserved', () => {
    const section = document.createElement('div');
    const { renderSkillGroup } = createScaffoldGalleryCards({ openDetail: vi.fn() });
    renderSkillGroup(section, 'my-skill', [
      { name: 'my-skill', status: 'framework', read_only: false },
      { name: 'my-skill/reference', status: 'framework', read_only: true },
    ]);

    // The picker must not be able to hide the fact by landing on the member
    // that happens to be writable: the reserved set covers whole subtrees.
    expect(qs(/** @type {HTMLElement} */ (section.firstElementChild), '.prompts-badge.read-only'))
      .toBeTruthy();
  });

  test('stays off an artifact whose payload carries no read_only key at all', () => {
    // The transitional shape: until the service stamps the flag, every entry
    // arrives without it. Absent must read as writable, not as unknown --
    // a badge on everything would be worse than a badge on nothing.
    const noFlag = withoutReadOnlyKey(WRITABLE);
    const card = renderCard(noFlag);

    expect(card.querySelector('.prompts-badge.read-only')).toBeNull();
    expect(card.classList.contains('prompts-card-readonly')).toBe(false);
  });

  test('repeats in the detail header of a reserved artifact', () => {
    const { gallery } = openDetail(RESERVED);

    expect(qs(gallery.detailHeaderEl, '.prompts-badge.read-only')).toBeTruthy();
  });

  test('is absent from the detail header of a writable artifact', () => {
    const { gallery } = openDetail(WRITABLE);

    expect(gallery.detailHeaderEl.querySelector('.prompts-badge.read-only')).toBeNull();
  });
});

describe('disabled write controls', () => {
  test('the save control is disabled for a reserved artifact even when dirty', () => {
    const { gallery, detail } = openDetail(RESERVED);
    // Edit mode is where the Save control renders at all. Its tab is disabled
    // for a reserved artifact, so this is the belt-and-braces case: even if
    // something else puts the panel into Edit and dirties it, Save stays shut.
    gallery.detailMode = 'edit';
    gallery.editDirty = true;
    detail.renderDetailModes();

    const saveBtn = /** @type {HTMLButtonElement} */ (qs(gallery.detailModesEl, '.prompts-save-btn'));
    expect(saveBtn.disabled).toBe(true);
    expect(saveBtn.title).toMatch(/build profile/i);
  });

  test('the save control still enables on a dirty writable artifact', () => {
    const { gallery, detail } = openDetail(WRITABLE);
    gallery.detailMode = 'edit';
    gallery.editDirty = true;
    detail.renderDetailModes();

    const saveBtn = /** @type {HTMLButtonElement} */ (qs(gallery.detailModesEl, '.prompts-save-btn'));
    expect(saveBtn.disabled).toBe(false);
    expect(saveBtn.title).toBe('');
  });

  test('the Edit tab is disabled for a reserved artifact but Preview stays open', () => {
    const { gallery } = openDetail(RESERVED);

    const buttons = /** @type {HTMLButtonElement[]} */ (
      Array.from(gallery.detailModesEl.querySelectorAll('.prompts-mode-btn'))
    );
    const byLabel = Object.fromEntries(buttons.map((b) => [b.textContent, b]));

    expect(byLabel['Edit'].disabled).toBe(true);
    expect(byLabel['Edit'].title).toMatch(/build profile/i);
    expect(byLabel['Preview'].disabled).toBe(false);
  });

  test('the ownership button is disabled for a reserved artifact', () => {
    const { gallery } = openDetail(RESERVED);

    const ownerBtn = /** @type {HTMLButtonElement} */ (
      qs(gallery.detailHeaderEl, '.prompts-ownership-btn')
    );
    // Claiming a reserved artifact is refused as a 409 (ScaffoldClaimError via
    // the app-level handler) -- offering the button live would be a promise
    // the panel cannot keep.
    expect(ownerBtn.disabled).toBe(true);
  });

  test('an artifact with no read_only key keeps every control live', () => {
    const noFlag = withoutReadOnlyKey(WRITABLE);
    const { gallery, detail } = openDetail(noFlag);
    // Save only renders in edit mode (or in settings.json's dirty Preview), so
    // this has to be a real edit session to have a save control to assert on.
    gallery.detailMode = 'edit';
    gallery.editDirty = true;
    detail.renderDetailModes();

    const editBtn = /** @type {HTMLButtonElement} */ (
      Array.from(gallery.detailModesEl.querySelectorAll('.prompts-mode-btn'))
        .find((b) => b.textContent === 'Edit')
    );
    const saveBtn = /** @type {HTMLButtonElement} */ (
      qs(gallery.detailModesEl, '.prompts-save-btn')
    );
    const ownerBtn = /** @type {HTMLButtonElement} */ (
      qs(gallery.detailHeaderEl, '.prompts-ownership-btn')
    );

    expect(editBtn.disabled).toBe(false);
    expect(saveBtn.disabled).toBe(false);
    expect(ownerBtn.disabled).toBe(false);
    expect(gallery.detailHeaderEl.querySelector('.prompts-readonly-note')).toBeNull();
  });

  test('an artifact with no read_only key renders a typeable editor', () => {
    const noFlag = withoutReadOnlyKey(WRITABLE);
    const gallery = /** @type {any} */ ({
      selectedArtifact: noFlag,
      editDirty: false,
      detailContentEl: document.createElement('div'),
      renderDetailModes: vi.fn(),
    });
    const { renderPlainTextEditor } = createScaffoldGalleryEditForm(gallery);
    renderPlainTextEditor('# Reviewer\n');

    const textarea = /** @type {HTMLTextAreaElement} */ (
      qs(gallery.detailContentEl, '.prompts-edit-textarea')
    );
    expect(textarea.readOnly).toBe(false);
  });

  test('the Edit tab and ownership button stay live for a writable artifact', () => {
    const { gallery } = openDetail(WRITABLE);

    const editBtn = /** @type {HTMLButtonElement} */ (
      Array.from(gallery.detailModesEl.querySelectorAll('.prompts-mode-btn'))
        .find((b) => b.textContent === 'Edit')
    );
    const ownerBtn = /** @type {HTMLButtonElement} */ (
      qs(gallery.detailHeaderEl, '.prompts-ownership-btn')
    );

    expect(editBtn.disabled).toBe(false);
    expect(ownerBtn.disabled).toBe(false);
  });
});

describe('read-only editors', () => {
  test('the plain-text editor is not typeable for a reserved artifact', async () => {
    const gallery = /** @type {any} */ ({
      selectedArtifact: RESERVED,
      editDirty: false,
      detailContentEl: document.createElement('div'),
      renderDetailModes: vi.fn(),
    });
    const { renderPlainTextEditor } = createScaffoldGalleryEditForm(gallery);
    renderPlainTextEditor('{"permissions": {}}');

    const textarea = /** @type {HTMLTextAreaElement} */ (
      qs(gallery.detailContentEl, '.prompts-edit-textarea')
    );
    expect(textarea.readOnly).toBe(true);
    expect(textarea.classList.contains('prompts-edit-readonly')).toBe(true);
  });

  test('the plain-text editor stays typeable for a writable artifact', () => {
    const gallery = /** @type {any} */ ({
      selectedArtifact: WRITABLE,
      editDirty: false,
      detailContentEl: document.createElement('div'),
      renderDetailModes: vi.fn(),
    });
    const { renderPlainTextEditor } = createScaffoldGalleryEditForm(gallery);
    renderPlainTextEditor('# Reviewer\n');

    const textarea = /** @type {HTMLTextAreaElement} */ (
      qs(gallery.detailContentEl, '.prompts-edit-textarea')
    );
    expect(textarea.readOnly).toBe(false);
  });

  test('the front-matter form disables its fields for a reserved artifact', () => {
    const gallery = /** @type {any} */ ({
      selectedArtifact: { ...RESERVED, name: 'reviewer', language: 'markdown' },
      editDirty: false,
      detailContentEl: document.createElement('div'),
      renderDetailModes: vi.fn(),
    });
    const { renderFrontMatterForm } = createScaffoldGalleryEditForm(gallery);
    renderFrontMatterForm('', { name: 'reviewer', model: 'opus' }, 'body');

    const inputs = /** @type {HTMLInputElement[]} */ (
      Array.from(gallery.detailContentEl.querySelectorAll('.prompts-fm-field input, .prompts-fm-field select'))
    );
    expect(inputs.length).toBeGreaterThan(0);
    expect(inputs.every((i) => i.disabled)).toBe(true);

    const bodyTextarea = /** @type {HTMLTextAreaElement} */ (
      qs(gallery.detailContentEl, '.prompts-edit-textarea')
    );
    expect(bodyTextarea.readOnly).toBe(true);
  });

  test("settings.json's Preview always renders read-only", async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({
        ok: true,
        json: async () => ({ content: '{"model": "opus"}', language: 'json' }),
      }))
    );
    const gallery = /** @type {any} */ ({
      selectedArtifact: RESERVED,
      detailContentEl: document.createElement('div'),
      editDirty: false,
      renderDetailModes: vi.fn(),
    });
    const { renderPreview } = createScaffoldGalleryDetailContent(gallery);

    await renderPreview();

    // The read-only structured view renders and nothing in it accepts input,
    // so saveOverride has nothing to pull edits out of and the dirty flag the
    // Save button reads never flips.
    expect(qs(gallery.detailContentEl, '.config-structured-view')).toBeTruthy();
    expect(gallery.detailContentEl.querySelectorAll('input, select, textarea')).toHaveLength(0);
    expect(gallery.editDirty).toBe(false);
  });
});

describe('panel copy', () => {
  test('the detail header says what to do instead of saving here', () => {
    const { gallery } = openDetail(RESERVED);

    const note = qs(gallery.detailHeaderEl, '.prompts-readonly-note');
    expect(note.textContent).toMatch(/build profile/i);
    expect(note.textContent).toMatch(/rebuild/i);
  });

  test('no such copy on a writable artifact', () => {
    const { gallery } = openDetail(WRITABLE);

    expect(gallery.detailHeaderEl.querySelector('.prompts-readonly-note')).toBeNull();
  });
});

describe('refused write', () => {
  /** @param {Partial<any>} [overrides] */
  function makeEditGallery(overrides = {}) {
    const detailContentEl = /** @type {any} */ (document.createElement('div'));
    const textarea = document.createElement('textarea');
    textarea.className = 'prompts-edit-textarea';
    textarea.value = 'edited';
    detailContentEl.appendChild(textarea);

    return /** @type {any} */ ({
      selectedArtifact: WRITABLE,
      artifacts: [],
      reloadFull: vi.fn(() => Promise.resolve()),
      currentView: 'detail',
      detailMode: 'edit',
      editDirty: true,
      detailContentEl,
      errorEl: document.createElement('div'),
      galleryView: document.createElement('div'),
      detailView: document.createElement('div'),
      onDetailClose: null,
      openDetail: vi.fn(),
      renderDetailModes: vi.fn(),
      renderDetailContent: vi.fn(),
      renderGallery: vi.fn(),
      ...overrides,
    });
  }

  /** Stub a refused write: 403 carrying the server's channel detail. */
  function stubRefusal() {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({
        ok: false,
        status: 403,
        json: async () => ({ detail: REFUSAL_DETAIL }),
      }))
    );
  }

  test('a refused save surfaces the channel detail verbatim in the banner', async () => {
    stubRefusal();
    const gallery = makeEditGallery();
    const { saveOverride } = createScaffoldGalleryEdit(gallery);

    await saveOverride();

    expect(gallery.errorEl.style.display).toBe('flex');
    // Intact, behind the prefix that says which action broke: the sentence
    // naming the owning channel is the whole point of the refusal and must not
    // be truncated or paraphrased on the way out.
    expect(gallery.errorEl.textContent).toBe(`Save failed: ${REFUSAL_DETAIL}`);
    expect(gallery.editDirty).toBe(true); // nothing was written, so nothing is clean
  });

  test('a refused claim surfaces its own 409 detail intact', async () => {
    // Deliberately not the save refusal: a claim is refused by a different
    // mechanism (ScaffoldClaimError -> 409) with different words, and the
    // banner has to carry whichever one the server actually sent.
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({
        ok: false,
        status: 409,
        json: async () => ({ detail: CLAIM_REFUSAL_DETAIL }),
      }))
    );
    const gallery = makeEditGallery({ selectedArtifact: RESERVED });
    const { takeOwnership } = createScaffoldGalleryEdit(gallery);

    await takeOwnership();

    expect(gallery.errorEl.textContent).toBe(`Scaffold failed: ${CLAIM_REFUSAL_DETAIL}`);
  });

  test('an ordinary failure still says which action broke', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => ({ ok: false, status: 500, json: async () => ({}) }))
    );
    const gallery = makeEditGallery();
    const { saveOverride } = createScaffoldGalleryEdit(gallery);

    await saveOverride();

    expect(gallery.errorEl.textContent).toContain('Save failed');
  });
});
