#!/usr/bin/env python3
"""The stub ``docker`` the pty harness puts on PATH. All behaviour is in _stub_main."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from _stub_main import main  # noqa: E402

sys.exit(main())
