"""Generate OSPREY's channel-limits database from the GEECS DB snapshot.

Input:  undulator_extract.json (same snapshot the channel database uses).
Output: ../overlays/data/channel_limits.json

One entry per settable variable's :SP PV, with min/max taken from the GEECS
DB limits where they exist. defaults.writable is false, and the profile pins
allow_unlisted_channels: false, so ONLY the :SP channels listed here are
writable through OSPREY's software layer. This mirrors — deliberately — the
same DB limits the gateway now enforces as EPICS control limits on :SP
channels; the duplication is defense-in-depth, and both derive from the one
authority (the GEECS DB), refreshed by the same extract.

Rerun after refreshing the snapshot:
    python extract_geecs.py Undulator   # needs lab network (GEECS DB)
    python generate_channel_limits.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).parent
EXTRACT = HERE / "undulator_extract.json"
OUT = HERE.parent / "overlays" / "data" / "channel_limits.json"

data = json.loads(EXTRACT.read_text())

doc: dict = {
    "_comment": (
        "HTU / Undulator channel limits. Generated by "
        "build-profile/tools/generate_channel_limits.py from the GEECS DB "
        "snapshot (same extract as the channel database) — do not hand-edit; "
        "rerun the generator. Writable surface: exactly the :SP setpoint PVs "
        "of settable GEECS variables, plus the gateway restart PV. min/max "
        "mirror the GEECS DB limits (also enforced gateway-side as EPICS "
        "control limits); entries without min/max are settable variables the "
        "GEECS DB does not bound — the device remains the authority."
    ),
    "_version": "2.0",
    "defaults": {
        "_comment": "Anything not listed below is refused (writable false; "
        "allow_unlisted_channels is false in config).",
        "writable": False,
        "verification": {"level": "callback"},
    },
}

n_bounded = n_unbounded = 0
for dev in sorted(data["devices"], key=lambda d: d["device"]):
    for v in dev["variables"]:
        if not v["settable"]:
            continue
        entry: dict = {"writable": True}
        if v["lo"] is not None:
            entry["min_value"] = v["lo"]
        if v["hi"] is not None:
            entry["max_value"] = v["hi"]
        if "min_value" in entry or "max_value" in entry:
            n_bounded += 1
        else:
            n_unbounded += 1
        doc[v["pv"] + ":SP"] = entry

# Gateway restart PV — the one client-writable PV in the gateway's own
# namespace (enum Idle/Restart, written directly, no :SP). Writing Restart
# cleanly restarts the gateway and re-syncs the served set; the per-write
# approval prompt still gates it.
doc["undulator:cagateway:restart"] = {"writable": True}

OUT.write_text(json.dumps(doc, indent=1))
print(f"wrote {OUT}")
print(f"writable :SP entries: {n_bounded + n_unbounded} (bounded: {n_bounded}, unbounded: {n_unbounded})")
